apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: vault-default-user
spec:
  replicas: 3
  secretBackend:
    vault:
      role: rabbitmq
      # Optionally, set Vault annotations as listed in
      # https://www.vaultproject.io/docs/platform/k8s/injector/annotations
      annotations:
        vault.hashicorp.com/template-static-secret-render-interval: "15s"
      defaultUserPath: secret/data/rabbitmq/config
      # Optionally, override the sidecar container image that rotates admin password in RabbitMQ server
      # whenever Vault sidecar container puts a new password into
      # If not specified, it defaults to "rabbitmqoperator/admin-password-updater:0.1.1"
      # /etc/rabbitmq/conf.d/11-default_user.conf
      # defaultUserUpdaterImage: "rabbitmqoperator/admin-password-updater:0.1.1"
