# action to test our operator lifecycle manager bundle
# See https://github.com/rabbitmq/OLM-Package-Repo for more info.
name: test-and-publish-OLM-bundle

on:
    push:
      # Pattern matched against refs/tags
      branches:
        - "testing_olm"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
env:
  # registry information where we want to store the operator image and the operator index image
  DOCKER_REGISTRY_SERVER: docker.io/rabbitmqoperator
  OLM_IMAGE: rabbitmq-for-kubernetes-olm
  OLM_INDEX_IMAGE: rabbitmq-for-kubernetes-olm-index
  OLM_IMAGE_TAG: 0.0.0

jobs:
    create-olm-package:
        name: Create the OLM Packaging
        runs-on: ubuntu-latest
        container: 
            image: us.gcr.io/cf-rabbitmq-for-k8s-bunny/rabbitmq-for-kubernetes-ci-olm
            options: --privileged
        permissions:
            contents: 'write'
            id-token: 'write'
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set released tag image
          if: startsWith(github.ref, 'refs/tags/v')
          run: | 
            OLM_IMAGE_TAG=${GITHUB_REF#refs/*/} 
            echo "OLM_IMAGE_TAG=${OLM_IMAGE_TAG:1}"
            export OLM_IMAGE_TAG  

        - name: Set test tag image
          if: startsWith(github.ref, 'refs/tags/v') == false
          run: | 
            OLM_IMAGE_TAG=${{ env.OLM_IMAGE_TAG }}
            export OLM_IMAGE_TAG  
            
        - name: create-olm-package
          env:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            DOCKER_REGISTRY_SERVER: ${{ env.DOCKER_REGISTRY_SERVER }}
            OLM_IMAGE: ${{ env.OLM_IMAGE }}
            OLM_INDEX_IMAGE: ${{ env.OLM_INDEX_IMAGE }}
          run: |   
            sed '/mount_program =/s/^#//' -i /etc/containers/storage.conf
            podman login -u $username -p $password
            git config --global --add safe.directory /__w/cluster-operator/cluster-operator
            git clone https://github.com/rabbitmq/OLM-Package-Repo -b using_dockerhub_instead_of_gcr
            make generate-installation-manifest
            cp ./config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml ./OLM-Package-Repo/generate_OLM/generate_OLM_cluster_operator/manifests_crds/crds.yaml
            cp ./releases/cluster-operator.yml ./OLM-Package-Repo/generate_OLM/generate_OLM_cluster_operator/manifests_crds/cluster-operator.yaml
            cp OLM-Package-Repo/generate_OLM/generate_OLM_cluster_operator/generators/cluster-service-version-generator-test.yml OLM-Package-Repo/generate_OLM/generate_OLM_cluster_operator/generators/cluster-service-version-generator.yml 
            cd ./OLM-Package-Repo/generate_OLM/generate_OLM_cluster_operator/
            python3 generate-olm-package.py ./manifests_crds/cluster-operator.yaml $OLM_IMAGE_TAG ./
            opm alpha bundle build -c stable -d ./$OLM_IMAGE_TAG/manifests -t $DOCKER_REGISTRY_SERVER/$OLM_IMAGE:$OLM_IMAGE_TAG -p rabbitmq-cluster-operator --image-builder podman
            echo "y" | gcloud auth configure-docker         
            podman push $DOCKER_REGISTRY_SERVER/$OLM_IMAGE:$OLM_IMAGE_TAG
            opm index add -b $DOCKER_REGISTRY_SERVER/$OLM_IMAGE:$OLM_IMAGE_TAG -t $DOCKER_REGISTRY_SERVER/$OLM_INDEX_IMAGE:$OLM_IMAGE_TAG -c podman
            podman push $DOCKER_REGISTRY_SERVER/$OLM_INDEX_IMAGE:$OLM_IMAGE_TAG
            mkdir upload
            mv "$OLM_IMAGE_TAG" ./upload
            cp ./generators/cluster-service-version-generator-openshift.yml ./generators/cluster-service-version-generator.yml
            python3 generate-olm-package.py ./manifests_crds/cluster-operator.yaml "$OLM_IMAGE_TAG" ./
            mv "$OLM_IMAGE_TAG" ./upload/$OLM_IMAGE_TAG-openshift
        - name: upload-olm-package
          uses: actions/upload-artifact@master
          with:
            name: olm-artifact
            path: "/home/runner/work/cluster-operator/cluster-operator/OLM-Package-Repo/generate_OLM/generate_OLM_cluster_operator/upload/"

    test-olm-package:
        name: Tests the OLM packaging
        runs-on: ubuntu-latest
        needs: create-olm-package
        container: us.gcr.io/cf-rabbitmq-for-k8s-bunny/rabbitmq-for-kubernetes-ci-olm
   
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Get Openshift connection info kubeconf from infrastructure repo
          env:
            GITHUB_ACCESS_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
          run: |
            git clone https://oauth2:"$GITHUB_ACCESS_TOKEN"@github.com/rabbitmq/infrastructure
            
        - name: Connect to the Openshift cluster and deploy the operators through OLM
          run: |   
            git clone https://github.com/rabbitmq/OLM-Package-Repo -b using_dockerhub_instead_of_gcr
            mkdir $HOME/.kube
            cp ./infrastructure/k8s/okd/admin-kubeconfig.yaml $HOME/.kube/config
            export KUBECONFIG=$HOME/.kube/config
            export ENVIRONMENT=openshift
            kubectl config use-context admin
            ./OLM-Package-Repo/testfiles/install-rabbitmq-cluster-operator.sh
            export K8S_OPERATOR_NAMESPACE=rabbitmq-system-olm
            export SYSTEM_TEST_NAMESPACE=rabbitmq-system-olm 
            make system-tests

        - name: Clean up
          if: always()
          run: | 
            export KUBECONFIG=./infrastructure/k8s/okd/admin-kubeconfig.yaml
            kubectl config use-context admin
            ./OLM-Package-Repo/testfiles/uninstall-rabbitmq-cluster-operator.sh

    publish-bundle:
        name: Publish on OperatorHub and Openshift market-place
        runs-on: ubuntu-latest
        # if: startsWith(github.ref, 'refs/tags/v')
        needs: test-olm-package
        container: us.gcr.io/cf-rabbitmq-for-k8s-bunny/rabbitmq-for-kubernetes-ci-olm
        # Create the PR to OperatorHUB
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: download olm-artifact from previous step
          uses: actions/download-artifact@master
          with:
            name: olm-artifact
        - name: CreateOperatorHubPR
          env:
            TOKEN: ${{ secrets.OPERATORHUB_TOKEN }}
          run: |
            git config --global user.name "DanielePalaia"
            git config --global user.email "dpalaia@vmware.com"
            git clone https://github.com/rabbitmq/community-operators
            mkdir -p community-operators/operators/rabbitmq-cluster-operator
            cd community-operators/operators/rabbitmq-cluster-operator
            git branch rabbitmq-cluster-operator-$OLM_IMAGE_TAG
            git checkout rabbitmq-cluster-operator-$OLM_IMAGE_TAG
            cp -fR ./../../../$OLM_IMAGE_TAG .
            git add .
            git commit -s -m "RabbitMQ operator new release"
            git push https://DanielePalaia:"$TOKEN"@github.com/rabbitmq/community-operators
            cd ./../../..
        
        # Create the PR to redhat openshift ecosystem
        - name: CreateOpenshiftEcosystemPR
          env:
            TOKEN: ${{ secrets.OPERATORHUB_TOKEN }}
          run: |
            git clone https://github.com/rabbitmq/community-operators-prod
            cd community-operators-prod/operators/rabbitmq-cluster-operator
            git branch rabbitmq-cluster-operator-$OLM_IMAGE_TAG
            git checkout rabbitmq-cluster-operator-$OLM_IMAGE_TAG
            cp -fR ./../../../$OLM_IMAGE_TAG-openshift .
            mv $OLM_IMAGE_TAG-openshift $OLM_IMAGE_TAG
            git add .
            git commit -s -m "RabbitMQ operator new release"
            git push https://DanielePalaia:"$TOKEN"@github.com/rabbitmq/community-operators-prod  